/**
 * ==========================================================
 * LÉLUVERSE
 * WHITECAPS
 *
 * Surface foam generated by wind and wave crests.
 *
 * Responsibilities
 * ----------------
 * • Floating whitecaps
 * • Wave crest foam
 * • Tide response
 * • Current movement
 * ==========================================================
 */

import { useFrame } from "@react-three/fiber";
import {
  useMemo,
  useRef,
} from "react";

import {
  Group,
  Mesh,
  DoubleSide,
} from "three";

import type { OceanState } from "../../Ocean";

interface Props {
  oceanState?: OceanState;
}

interface Whitecap {

  x: number;

  y: number;

  z: number;

  rx: number;

  ry: number;

  rz: number;

  size: number;

  speed: number;

  offset: number;

  opacity: number;

}

export default function Whitecaps({
  oceanState = {},
}: Props) {

  const group =
    useRef<Group>(null);

  const time =
    useRef(0);

  const caps =
    useMemo<Whitecap[]>(() => {

      return Array.from({

        length: 180,

      }, (): Whitecap => ({

        x:
          (Math.random() - 0.5) * 4.7,

        y:
          2.22 +
          Math.random() * 0.04,

        z:
          (Math.random() - 0.5) * 4.7,

        rx:
          -Math.PI / 2,

        ry:
          Math.random() *
          Math.PI * 2,

        rz:
          Math.random() *
          Math.PI * 2,

        size:
          0.02 +
          Math.random() * 0.08,

        speed:
          0.2 +
          Math.random() * 0.4,

        offset:
          Math.random() * 100,

        opacity:
          0.08 +
          Math.random() * 0.14,

      }));

    }, []);

  useFrame((_, delta) => {

    if (!group.current)
      return;

    time.current += delta;

    const tide =
      oceanState.tide ?? 0.5;

    const current =
      oceanState.current ?? 0.5;

    group.current.children.forEach(
      (child, i) => {

        const mesh =
          child as Mesh;

        const cap =
          caps[i];

        mesh.position.x =
          cap.x +
          Math.sin(
            time.current *
            cap.speed +
            cap.offset,
          ) *
          0.12 *
          current;

        mesh.position.z =
          cap.z +
          Math.cos(
            time.current *
            cap.speed +
            cap.offset,
          ) *
          0.12 *
          current;

        mesh.position.y =
          cap.y +
          Math.sin(
            time.current *
            2 +
            cap.offset,
          ) *
          0.015 *
          tide;

        mesh.rotation.z +=
          delta *
          0.35;

        const pulse =
          1 +
          Math.sin(
            time.current *
            3 +
            cap.offset,
          ) *
          0.25;

        mesh.scale.setScalar(
          cap.size *
          pulse,
        );

      },
    );

  });

  return (

    <group ref={group}>

      {caps.map((
        cap,
        i,
      ) => (

        <mesh

          key={i}

          position={[
            cap.x,
            cap.y,
            cap.z,
          ]}

          rotation={[
            cap.rx,
            cap.ry,
            cap.rz,
          ]}

        >

          <circleGeometry
            args={[
              1,
              16,
            ]}
          />

          <meshBasicMaterial

            color="#ffffff"

            transparent

            opacity={
              cap.opacity
            }

            side={
              DoubleSide
            }

            depthWrite={false}

          />

        </mesh>

      ))}

    </group>

  );

}